#

## TP 1 Projets Numériques

#

Dans le module Projets Numériques-MEPY3, vous utiliserez des outils de programmation pour résoudre des problèmes de mécanique/physique.
Les différents thèmes abordés seront traités en utilisant exclusivement les documents de travail "Notebook-Jupyter".

Dans un premier temps (2 séances TPs), les bases de la programmation **Python** seront présentées, afin de voir (ou revoir) le socle indispensable à la résolution numérique de problème. Ces outils seront mis en oeuvre lors de la réalisation des projets (3 séances Projet).

Le sujet est découpé en deux parties :

- le travail de découverte des notions à réaliser en séance ;
- le travail de mise en \oe uvre des notions à réaliser en autonomie et déposer sur Moodle une semaine plus tard (voir le calendrier des dépôts sur Moodle). Vous pourrez utiliser le bureau à distance de _CAPSULE_ pour accéder à vos fichiers.

Pour vous aider, vous pourrez vous référer au memento fourni dans le module, ou bien aux nombreux sites web présentant les commandes **Python**, comme par exemple

- https://courspython.com/
- https://python.sdv.univ-paris-diderot.fr
- https://docs.python.org/ La langue et la version peuvent être sélectionnées en haut à gauche.
- Cours PDF téléchargeable : https://www.licence.info.upmc.fr/lmd/licence/2019/ue/LU1IN001-2019oct/elemprog_2019-09-10.pdf


# ----------------------------------------------------------------------------------

### Partie I. Affichage et format

Pour afficher un résultat à l’écran, on utilise la fonction $\mathtt{print(arguments)}$. Les arguments peuvent être des chaînes de caractères (placés entre guillemets $"  "$) ou bien des valeurs contenues dans des variables (désignées par des lettres ou mots). Les arguments seront séparés par des virgules.

La cellule qui suit (**In [1]:**) donne quelques exemples d'affichage.

**Note**: 'sep' spécifie un séparateur entre les différents arguments à afficher et '#' spécifie le début des commentaires, instructions non lues et non exécutées par Python.


In [98]:
# je debute en python....
print("Mon premier code") # Exemple
a=10; b=2
c= 2023
print(a,b)
print(a,b,sep=" ; ")
print(a,"séances de",b,"heures") # signification de a et b

Mon premier code
10 2
10 ; 2
10 séances de 2 heures


#### >>>>> Q 1) Affecter la valeur $50$ à la variable Var, puis l'afficher sous la forme $\mathtt{Var=50}$. Faire de même pour la variable x_negatif et la valeur $-2,5$. On pourra écrire les instructions d'affectation et d'affichage sur une même ligne, en les séparant par un point-virgule " ; ".

**Note 1**: Python fait la différence entre les minuscules et les majuscules, on dit qu'il est sensible à la casse.

**Note 2**: En python comme dans la plupart (si ce n'est tous) des languages de programmation, les variables ont un _type_ associé qui change la manière dont est encodée la mémoire allouée à la variable dans la machine. Plusieurs types peuvent décrire les variables, dont entiers / réel / caractère / booléen.
Par exemple, le chiffre 4 est un entier ou _integer_ en anglais. Si on pose $x=4$, la valeur $4$ sera allouée à la variable $x$ qui sera donc un _integer_. Si on tape la commande $\mathtt{print(x)}$, la cellule devrait renvoyer le chiffre $4$. En revanche, si on alloue la valeur $4.00$ à $x$, il n'est pas considéré comme un entier mais un nombre réel à virgule "flottante" d'où sa dénomination _float_ en anglais. Il faut bien comprendre que $4$ et $4.0$ sont des valeurs fondamentalement différentes pour la machine, elles ne seront pas traitées de la même manière. Par exemple, si on relance la commande $\mathtt{print(x)}$ après la nouvelle allocation, le résultat affiché devrait être $4.0$ (peu importe le nombre de $0$ après la virgule dans l'allocation).


In [99]:
# Affichage des valeurs de variables
Var=50; x=-2.5
print("Var=",Var); print('x_negatif=',x)

Var= 50
x_negatif= -2.5


#### >>>>> Q 2) Afficher sous la forme de 3 colonnes les résultats à l'examen des 4 étudiants Pierre, Paul, Jacques et Sophie qui ont obtenu respectivement 12, 8, 16, 15 (sur 20) en Math et 10, 15, 13, 17 en Physique.

On affichera une ligne d'en-tête spécifiant ce que représente chaque colonne.


In [100]:
# Affichage des notes
print('Nom ', 'Math ', 'Physique ')
print('Pierre ',12,10)
print('Paul ',8,15)
print('Jacques ',16,13)
print('Sophie ',15,17)

Nom  Math  Physique 
Pierre  12 10
Paul  8 15
Jacques  16 13
Sophie  15 17


# -----------------

Afin de faciliter la lecture des résultats, on peut utiliser l'écriture formatée du contenu des variables. On utilise les commandes _f-string_ (_string_ désigne une chaîne de caractères):
print(f"{ }")

Par exemple, pour une variable $\mathtt{x}$ :

- $\mathtt{\{x:d\}}$ affiche un entier (_integer_) ;
- $\mathtt{\{x:10s\}}$ affiche une chaîne de caractères de taille maximale 10 caractères ;
- $\mathtt{\{x:7.2f\}}$ affiche un réel (_float_) avec deux chiffres après la virgule sur une réservation d'espace de sept caractères.

Attention, il faut respecter le type des variables (entiers / réel / caractère / booléen). La fonction $\mathtt{type}()$ permet de se renseigner sur le type d'une variable.
La cellule qui suit vous donne quelques exemples.


In [101]:
# Exemples d'affichage formaté
a=2.351; b=5
print(f"{b:d}")
print(f"{a:}"); print(f"{a:7.3f}");  print(f"{a:7.2f}")
print(type(b));print(type(a))
print(f"a ={a:7.3f}")
print(f"a ={a:7.3f}\t b={b}")
print(f"dernier affichage a ={a:7.3f}\n b={b}")


5
2.351
  2.351
   2.35
<class 'int'>
<class 'float'>
a =  2.351
a =  2.351	 b=5
dernier affichage a =  2.351
 b=5


#### >>>>> Q 3) Reprendre l'exemple des notes-etudiants pour afficher 3 colonnes bien délimitées en taille.


In [102]:
# Affichage des notes
n1='Pierre'; m1=12; p1=10
n2='Paul'; m2=8; p2=15
n3='Jacques'; m3=16; p3=13
n4='Sophie'; m4=15; p4=17
n0='Nom'; m0='Math'; p0='Phys'
print(f' {n0:10s} {m0:4s} {p0:4s} ')
print(f' {n1:10s} {m1:4d} {p1:4d} ')
print(f' {n2:10s} {m2:4d} {p2:4d} ')
print(f' {n3:10s} {m3:4d} {p3:4d} ')
print(f' {n4:10s} {m4:4d} {p4:4d} ')


 Nom        Math Phys 
 Pierre       12   10 
 Paul          8   15 
 Jacques      16   13 
 Sophie       15   17 


# --------------------------------------------------------------------------

### Partie II. Opérateurs arithmétiques et fonctions prédéfinies

Pour composer des expressions arithmétiques, **Python** utilise :

- des opérateurs arithmétiques
- des fonctions prédéfinies en langage Python ou définies par le programmeur (cf. TP2).

Des opérateurs usuels (qui travaillent sur des nombres et renvoient des nombres) sont :

    L'addition : **+** , la soustraction ou signe moins : **-** , la mutiplication : *****
    L'exponentiation (mise à la puissance) de A par B : A******B
    La division de A par B : A/B
    La division euclidienne (division entière) de A par B : A//B
    Le reste de la division euclidienne de A par B : A%B


#### >>>>> Q 4) Convertir ou calculer les données suivantes :

Convertir v = 50 km h$^{-1}$ en ... m s$^{-1}$.

Convertir F = 300 N en ... kg m s$^{-2}$. Donner le "poids" équivalent en "kg".

Convertir rho= 1000 kg m$^{-3}$ en ... g cm$^{-3}$.

Calculer l'énergie cinétique d'une voiture de 1,5 tonnes roulant à 130 km h$^{-1}$.


In [103]:
# conversions
v=50 #kmh-1
v_SI=v*1000/3600 # ms-1
print(v_SI,'ms-1'); print(f'{v_SI:4.2f} ms-1')
F=300
print(F,'kgms-2','poids equivalent ',F/10,'kg')
rho=1000
print(rho*1000*1e-6 ,'gcm-3')
print('Ec pour la voiture de 1.5 tonnes roulant à 130km/h',.5*1.5e3*(130*1e3/3600)**2,' J')

13.88888888888889 ms-1
13.89 ms-1
300 kgms-2 poids equivalent  30.0 kg
1.0 gcm-3
Ec pour la voiture de 1.5 tonnes roulant à 130km/h 978009.2592592593  J


#### >>>>> Q 5) Examiner l'exemple suivant. Comparer les deux dernières lignes et améliorer l'affichage du nombre d'enfants (entier) dans celles-ci en utilsant les trois méthodes suivantes:

commande $\mathtt{int}()$, division entière ("//"), format spécifique f-string.


In [104]:
x = 56 ; nom = "John"
print(x/14, x//14, int(x/14))
print(nom, "a", x, "ans et", nom, "a", x/14, "enfants")
print(f"{nom} a {x} ans et {nom} a {x/14} enfants")


4.0 4 4
John a 56 ans et John a 4.0 enfants
John a 56 ans et John a 4.0 enfants


In [105]:
# Ecriture de la ligne "John a 56 ans et John a 4 enfants"
#Ma version
print(f"{nom} a {x} ans et {nom} a {int(x/14)} enfants")


John a 56 ans et John a 4 enfants


#### >>>>> Q 6) Calculer les expressions mathématiques qui suivent et afficher les résultats.

On considèrera $a = 2$, $b = 4$, $c = 3$, $d = 5$ :

- $f=(a+b)\cdot c$, $g=a+b\cdot c$, $h=a+(b\cdot c)$, $\Delta=b^2-4 \cdot a \cdot c$,
- $i=\dfrac{a}{b\cdot c-d}$, $j=\dfrac{a}{b \cdot (c-d)}$.

Attention à la priorité des opérateurs et à la position des parenthèses !


In [106]:
# Calculs
a = 2; b = 4; c = 3; d = 5
f = (a+b) * c
g = a + b * c
h = a + (b * c)
delta = b**2 - (4 * a * c)
i = a/(b*c-d)
j = a/(b*(c-d))


#### >>>>> Q 7) Calculer le quotient de la division entière de $\mathtt{a=17}$ par $\mathtt{b=5}$, et le reste appelé $\mathtt{Reste}$. On affichera le résultat de manière lisible.


In [107]:
# quotient/reste
a=17; b=5
quotient=a//b; reste=a%b
print(f"La division entière de a {a}/{b} = {quotient} et comme le reste on a = {reste}")


La division entière de a 17/5 = 3 et comme le reste on a = 2


# --------

Le langage **Python** fournit un grand nombre de _fonctions intrinsèques_ (c'est-à-dire qu'elles sont déjà définies). Elles sont donc accessibles directement. On peut citer par exemple : $\mathtt{max}()\mathtt{, min}()\mathtt{, abs}()$.

D'autres peuvent être appelées à partir d'une bibliothéque spécifique, pré-existante dans la suite **Python**, comme par exemple la bibliothèque _math_ pour l'arithmétique (exemples $\mathtt{cos}()\mathtt{,sin}()\mathtt{,sqrt}()\mathtt{,pi}$).

Pour pouvoir utiliser une fonction qui se trouve dans une bibliothèque, il faut tout d’abord
importer le module correspondant à cette bibliothèque, par l'instruction suivante : $\mathtt{import \, nom}\_\mathtt{module \, as\, nom}\_\mathtt{alias}$

L'_alias_ permet d'appeler le module sans avoir à réécrire son nom complet (qui peut être assez étendu) tout au long du code. Par exemple pour le module $\mathtt{math}$, il est d'usage d'écrire : </font>


In [108]:
import math as m

#### >>>>> Q 8) Que renvoient les instructions : $\mathtt{max?}$ et $\mathtt{m.sin?}$ ? (testez-les !). Déterminer le maximum et le minimum parmi les nombres 3,-8.2,5,12.3. Calculer le sinus de 30°.


In [109]:
print("le max est=", max(3, -8.2, 5, 12.3))
print("le min est=", min(3, -8.2, 5, 12.3))

le max est= 12.3
le min est= -8.2


In [110]:
m.sin(30*m.pi/180)


0.49999999999999994

In [111]:
# Max Min sinus
max(3,-8.2,5,12.3)
m.sin(30*3.14/180); m.sin(30*m.pi/180)
print(f'{m.sin(30*m.pi/180):4.2f}')

0.50


#### >>>>> Q 9) Calculer l'aire des deux triangles $T_1 =\mathtt{(ABC)}$ et $T_2 =\mathtt{(ABH)}$ de la figure ci-dessous, avec $b = 4 ~cm$, $\theta ~= 30^\circ$ et $h = 4.25 ~cm$. On donnera la valeur de l'angle $\alpha$ en degrés.

<img src="triangle_1.png" alt="triangles" width="400"/>


In [112]:
# Aire des Triangles
h = 4.25 #cm
theta = 30*m.pi/180 #degrés
b = 4 #cm
a = b*m.tan(theta) #cm 
c = a**2 +b **2 #cm

T1 = 0.5 * b * a




# -------------------------------------------------------------------------------------

### Partie III. Opérateurs logiques et boucles/iterations

La vérité logique est représentée par
l’expression _True_ qui signifie vrai et l’expression _False_ qui signifie faux. Ces deux expressions
forment le type booléen dénoté $\mathtt{bool}$, qui n'a donc que deux valeurs possibles : _True_ ou _False_. A partir de là, on peut construire des tests qui renverront une valeur booléenne.

Les expressions booléennes sont le plus souvent constituées de :

    Test d'égalité : ==
    Test d'inégalité : !=
    Test d'infériorité stricte : <
    Test d'infériorité large : <=
    Test de supériorité stricte : >
    Test de supériorité large : >=


pour comparer des nombres. Par ailleurs, on peut combiner les opérateurs logiques avec les connecteurs suivants : $\mathtt{and}$ pour "et", $\mathtt{or}$ pour "ou", $\mathtt{not}$ pour "non" qui prend le contraire de la condition logique testée.

Ces tests sont utiles pour construire des _alternatives_ qui proposent des choix. La syntaxe est la suivante (notez l'indentation après chaque ligne de test)':

```python
if(condition1):
     consequence1
elif(condition2):
     consequence2
else:
     consequence3
```

Ainsi, si la $\mathtt{condition1}$ vaut _True_ alors la $\mathtt{consequence1}$ sera exécutée. Sinon (la première condition vaut donc _False_) la deuxième condition est testée, si elle est vraie la deuxième conséquence est exécutée. Enfin si les deux conditions (toutes les conditions précédentes) sont fausses la dernière conséquence est donc appliquée.

On peut ajouter autant de tests que l'on souhaite. **Attention** à bien respecter l'identation pour les conséquences.


#### >>>>> Q 10) Ecrire un programme test concernant le triangle T1: est-il isocèle (2 côtés égaux), équilatéral (3 côtés égaux), quelconque?


In [113]:
# Test du triangle T1
b=4; theta=30*m.pi/180
a=b*m.tan(theta); 
c=a**2+b**2
if (a == b or b == c or c == a):
    print('triangle isocele')
elif (a == b and a == c):
    print('triangle equilateral')
else:
    print('triangle quelconque')
    

triangle quelconque


# --------

Pour réaliser des opérations répétitives, on peut utiliser deux types de boucles : avec $\mathtt{while}$ (_tant que_ ... quand on a un test) et $\mathtt{for}$ (_pour_ ... quand on connait la séquence d'indices à parcourir). Les syntaxes sont les suivantes :

```python
while(condition):
     corps
```

```python
for <index> in <intervalle>:
     corps
```

$\mathtt{index}$ est un indice, et $\mathtt{intervalle}$ sera l'instruction $\mathtt{range(m,n)}$, qui construit l’intervalle des entiers allant de m (inclus) à n (exclu), soit $[m;n-1]$. Par défaut, quand $m$ n'est pas précisé, $m=0$.

**Attention**

- à bien respecter l'identation du corps d'instruction.
- dans le cas des boucles $\mathtt{while}$, vous devez inclure une modification de la condition au sein du corps de la boucle. Si vous ne faites pas attention, vous risquez d'écrire _une boucle qui ne termine pas_ et votre code tournera jusqu'à ce qu'ennui s'en suive. Vous pouvez utiliser la commande $\mathtt{break}$ pour sortir de la boucle actuelle sans avoir à attendre la fin.

Deux exemples simples de boucles while et for (impression des entiers de 1 à 4) sont donnés dans la cellule qui suit.


In [114]:
# avec while
m=5; i=1
while(i<m):
    print(i,end=" ")
    i=i+1
print("fin")
# avec for
m=5
for i in range (1,m):
    print(i,end=" ")
print("fin")

1 2 3 4 fin
1 2 3 4 fin


#### >>>>> Q 11) Ecrire de deux façons (avec $\mathtt{while}$ et $\mathtt{for}$) une boucle qui fait la somme des 5 premiers entiers. Le résultat sera stocké dans une variable appelée $\mathtt{s}$.


In [115]:
# Somme des 5 premiers entiers
s=0
for i in range(1,6):
    s=s+i
print(s)

i=0; s=0
while(i<6):
    s=s+i
    i=i+1
print(s)

15
15


# ---------------------------------------------------------------------------------------

### Partie IV. Tableaux Numpy

En mécanique - physique, on traite souvent de la même manière un grand nombre de valeurs homogènes (par exemple issues de mesures). Pour faciliter leur traitement, on les sauvegarde dans des tableaux ("arrays" en anglais), construits à partir de la bibliothèque _Numpy_.
La bibliothèque _Numpy_ contient un très grand nombre d'opérateurs mathématiques qui peuvent agir directement sur ces tableaux (pour être précis, sur les composantes de ces tableaux).

Tout d'abord, il faut charger cette bibliothèque en utilisant l'expression $\mathtt{import}$, puis simplifier son nom à l'aide du mot-clé $\mathtt{as}$, de façon à limiter les écritures. Il est courant d'appliquer l'instruction suivante :


In [116]:
import numpy as np

Les tableaux Numpy contenant des ensembles de données homogènes de tailles
fixes (liste d’entiers, vecteurs réels ou complexes, matrices...) seront de type
_ndarray_. Attention, les tableaux NumPy ont beau avoir beaucoup de points communs avec les _listes_ que vous avez peut être déjà rencontré, ces deux objets sont vraiment différents (taille dynamique, types acceptés, opérations globales, concaténation...) et ne doivent pas être confondus.

**Mise en garde**: Au sein de ce module, on utilisera exclusivement les tableaux Numpy.

La taille et le type des éléments d’un tableau Numpy **doivent être connus à l’avance**. On crée donc en premier lieu un tableau rempli de zéros $\mathtt{np.zeros}()$ ou de uns $\mathtt{np.ones}()$ de la bonne taille et forme, avec un type de variable que l'on peut imposer (argument optionnel $\mathtt{dtype}$). Le type des éléments du tableau Numpy array1 peut être déterminé par $\mathtt{array1.dtype}$.

On peut aussi directement affecter des valeurs dans un tableau en utilisant le constructeur :$\mathtt{np.array([[ , , , ],[ , , , ], \textrm{etc...}])}$, où les $\mathtt{[ , , , ]}$ matérialisent les contenus du tableau pour la variation du dernier indice, soit typiquement en 2D une ligne (on fait varier l'indice de colonne).

On se déplace dans un tableau par des <font color='red'>indices **commençant à 0**</font>. Un tableau 1D - appelé aussi vecteur - a 1 indice variable, un tableau 2D a 2 indices variables, et un tableau 3D a 3 indices.

On pourra utiliser les commandes $\mathtt{array1.dtype}$ et $\mathtt{array1.shape}$ pour vérifier le type et la taille des tableaux. Pour un vecteur, on pourra utiliser $\mathtt{len(vec)}$ pour obtenir le nombre d'éléments de celui-ci.


#### >>>>> Q 12) Afficher le contenu des 5 tableaux ci-dessous, qu'on nommera A, B, C, D, E avec la commande $\mathtt{print}()$. Spécifier la dimension de chaque tableau et comprendre le rangement de ses éléments.


In [117]:
array0 = np.zeros(3, dtype=int) # vecteur de 3 entiers
array1 = np.zeros((2,4), dtype=float) # tableau de flottants de taille 2x4

array3 = np.array([2,4,5,7]) # vecteur d'entiers
array4 = np.array([[1.1,2.2],[1.4,2.4],[0,-1.77]]) # matrice de taille 3 x 2 remplie de réels

array2 = np.ones((3,2,5)) # tableau tridimensionnel de flottants

In [120]:
# Affichage des tableaux
print(array0,"\n"); print(array1,"\n") ; print(array3,"\n"); print(array4,"\n"); print(array2,"\n")

[0 0 0] 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[2 4 5 7] 

[[ 1.1   2.2 ]
 [ 1.4   2.4 ]
 [ 0.   -1.77]] 

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]] 



#### >>>>> Q 13) Reprendre l'exemple ci-dessus (4 premiers tableaux) pour afficher les valeurs de array3[1], array4[1,0] et array4[0,1], array4[2,1] et array4[1,2]. Commenter.


In [121]:
# affichage de certaines valeurs 
#Array 3[1]
print("valeur de array3[1] =", array3[1])
#Array 4[1,0]
print("valeur de array4[1,0] =", array4[1,0])
#Array 4[0,1]
print("valeur de array4[0,1] =", array4[0,1])
#Array 4[2,1]
print("valeur de array4[2,1] =", array4[2,1])
#Array 4[1,2]
print("valeur de array4[1,2] =", array4[1,2])
#Pour l'array 4 [1,2] cela ne marche pas parce qu'il cherche le valeur 3x2 du tableu
#qu'il n'existe pas dans le tableu 2 x 3


valeur de array3[1] = 4
valeur de array4[1,0] = 1.4
valeur de array4[0,1] = 2.2
valeur de array4[2,1] = -1.77


IndexError: index 2 is out of bounds for axis 1 with size 2

#### >>>>> Q 14) Tester les commandes suivantes. Elles illustrent la signification des mots-clés $\mathtt{(-1,-2,:)}$. Expliquer.

#### >>>>> Modifier ensuite la valeur du dernier éléments de array3 pour lui donner une valeur double.


In [122]:
# Test des commandes
array3 = np.array([2,4,5,7])
print (f"array3[:]={array3[:]}")
print (f"array3[0]={array3[0]}")
print (f"array3[-1]={array3[-1]}")
print (f"array3[0:-1]={array3[0:-1]}")
print (f"array3[0:2]={array3[0:2]}")
print (f"array3[0:]={array3[0:]}")
print (f"array3[-2]={array3[-2]}")
print (f"array3[:-2]={array3[:-2]}")
print(f"\n")

#Le command " -1 " prendre le dernier élément de la liste, et le " -2 "" prendre l'avant dernier.
#Pour le command " : " il prendre toutes les valeurs entre les nombres x : y, depuis le nombre qu'il y a dans la position
#de la gauche  des deux points (x) jusqu'à le nombre qu'il y a dans la position de le nombre de la droite (y) dans l'array

array3[:]=[2 4 5 7]
array3[0]=2
array3[-1]=7
array3[0:-1]=[2 4 5]
array3[0:2]=[2 4]
array3[0:]=[2 4 5 7]
array3[-2]=5
array3[:-2]=[2 4]




Commentaire :

- ($\mathtt{-1}$) désigne le dernier élément de l'indice, ($\mathtt{-2}$) l'avant dernier ;
- **Attention, l'indice de fin de plage ($\mathtt{debut:fin}$) n'est jamais atteint !!!** La boucle implicite s'arrête juste avant.
- si on ne précise pas le début ou la fin de la plage, on parcourt la plage jusqu'à l'extrêmité non explicitée.


In [123]:
# Modification de array3
i = 3
while (i>2):
    array3[i] = array3[i] * 2
    i = i - 1
    
print(array3)


[ 2  4  5 14]


# -------------

Pour créer rapidement des vecteurs avec un nombre d'éléments fixé dans un intervalle donné, des fonctions pré-définies Numpy existent:

- $\mathtt{np.arange}$
- $\mathtt{np.linspace}$

  - $\mathtt{np.arange(a,b,d)}$ crée le vecteur de valeurs dans [a,b[ avec un pas d.
  - $\mathtt{np.linspace(a,b,n)}$ crée le vecteur de n valeurs dans [a,b].

Les deux fonctions sont très utiles pour générer par exemple un jeu d'indices, un jeu de coordonnées (x ou y ou z,...), ...
Le code ci-dessous permet de comprendre les deux types d'instruction.


In [124]:
A=np.arange(0,11,1); print(A)
B=np.linspace(0,10,11); print(B)
vect0 = np.arange(5); print(vect0)
vect1= np.arange(2,5); print(vect1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0 1 2 3 4]
[2 3 4]


#### >>>>> Q 15) Générer et afficher à l'écran les vecteurs vect2=[0 2 4], vect3=[2.5 5.0 7.5], vect4=[-4.0 -3.0 -2.0 -1.0 0], vect5=[-1.5 -1. -0.5 0. 0.5 1. 1.5 2. ] en utilisant $\mathtt{np.arange}$.

Ne pas hésiter à utiliser l'aide ($\mathtt{np.arange?}$}$).


In [125]:
# vecteurs N° 2,3,4,5 avec np.arange
vect2 = np.arange(0,5,2); print("vect2 =", vect2)
vect3 = np.arange(2.5,10,2.5); print("vect3 =", vect3)
vect4 = np.arange(-4.0,1,1); print("vect4 =", vect4)
vect5 = np.arange(-1.5,2.5,0.5); print("vect5 =", vect5)


vect2 = [0 2 4]
vect3 = [2.5 5.  7.5]
vect4 = [-4. -3. -2. -1.  0.]
vect5 = [-1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]


# ---------

Des opérations arithmétiques sont possibles sur les tableaux Numpy.
**Attention**, on différenciera les opérations _élémentaires_ (chaque élément du tableau est concerné individuellement par l'opération suivant sa place dans le tableau), des opérations _matricielles_.

- opérations élémentaires : $\mathtt{+,-,*}$, mais aussi des fonctions mathématiques Numpy comme $\mathtt{np.cos, np.exp}$.
- produit matriciel. 3 écritures pour la même opération mathématique : $\mathtt{np.dot(mat1,mat2)}$, $\mathtt{mat1.dot(mat2)}$,$\mathtt{mat1@mat2}$.


#### >>>>> Q 16) On se propose de tester les opérations sur des tableaux qui seront des vecteurs:

1. Créer deux vecteurs $V1$ et $V2$ de longueur 10, variant entre 1 et 10.
2. Diviser chaque élément de $V1$ par 10. Ajouter 10 à chaque élément de $V2$
3. Mettre à zéro tous les éléments de $V1$ supérieurs stricts à 0.5. Idem pour les éléments de V2 impairs.


In [126]:
#q.1
V1 = np.linspace(1,10,10); 
V2 = np.arange(1,11,1); 

#q.2
print("Avant le boucle while \n V1 =", V1[:],"\n V2 =",V2[:],"\n")
i = 0 
while(i<10):
    V1[i] = V1[i]/10
    V2[i] = V2[i] + 10
    i = i + 1

print("Après le boucle while \n V1 =", V1[:],"\n V2 =",V2[:],"\n")

#q.3
i = 0
while(i<10):
    if(V1[i]>0.5):
        V1[i] = 0
    if(V2[i]%2 != 0):
        V2[i] = 0
    i = i + 1
print("Après le deuxième boucle while \n V1 =", V1[:],"\n V2 =",V2[:])



Avant le boucle while 
 V1 = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] 
 V2 = [ 1  2  3  4  5  6  7  8  9 10] 

Après le boucle while 
 V1 = [0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ] 
 V2 = [11 12 13 14 15 16 17 18 19 20] 

Après le deuxième boucle while 
 V1 = [0.1 0.2 0.3 0.4 0.5 0.  0.  0.  0.  0. ] 
 V2 = [ 0 12  0 14  0 16  0 18  0 20]


# Quelques exercices supplémentaires de révision portant sur ce TP1.

## A traiter en plus des questions du notebook non corrigées en séance.

## <font color='red'> >> Le travail est à réaliser en autonomie et à rendre sur Moodle individuellement dans 1 semaine (voir le tableau des dates de rendu sur Moodle). Tout retard sera pénalisé. </font>

---

---


#### #### Exercice N 1 : Tester les expressions suivantes :

$\mathtt{c=a/b}$,$\mathtt{d=a//b}$, $\mathtt{e=17/5}$, $\mathtt{f=17.0/5.0}$ .
Même chose avec $\mathtt{a=16}$ et $\mathtt{b=4}$.

Expliquer les raisons des différences obtenues en testant les types des variables (on utilisera le mot-clé $\mathtt{type}$, voir le memento).


In [127]:
# réponse N1 
a = 16; b = 4; 
c = a/b; d = a//b; e = 17/5; f = 17.0/5.0

print("Le valeur de c: ", c, "Le valeur de d: ", d,"Le valeur de e: ",e, "Le valeur de f:", f)

#Les différences dans les types de variables résultent de la manière dont Python effectue les opérations mathématiques en fonction des types de données des opérandes. 
#Les opérations entre des entiers donnent généralement des entier tels que c = a/b, e = 17/5
#tandis que les opérations avec au moins un nombre à virgule flottante donnent un résultat à virgule flottante d = a//b et f = 17.0/5.0

Le valeur de c:  4.0 Le valeur de d:  4 Le valeur de e:  3.4 Le valeur de f: 3.4


#### #### N 2 : Générer et afficher à l'écran les vecteurs vect2=[0 2 4], vect3=[2.5 5.0 7.5], vect4=[-4.0 -3.0 -2.0 -1.0 0], vect5=[-1.5 -1. -0.5 0. 0.5 1. 1.5 2. ] en utilisant $\mathtt{np.linspace}$.

Ne pas hésiter à utiliser l'aide ($\mathtt{np.linspace?}$).


In [128]:
# réponse N2

# vecteurs N° 2,3,4,5 avec np.arange
vect2 = np.arange(0,5,2); print("vect2 =", vect2)
vect3 = np.arange(2.5,10,2.5); print("vect3 =", vect3)
vect4 = np.arange(-4.0,1,1); print("vect4 =", vect4)
vect5 = np.arange(-1.5,2.5,0.5); print("vect5 =", vect5)


vect2 = [0 2 4]
vect3 = [2.5 5.  7.5]
vect4 = [-4. -3. -2. -1.  0.]
vect5 = [-1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]


#### #### N3 : On cherche à calculer le produit scalaire de deux vecteurs

1. Créer deux vecteurs _vect_a_ et _vect_b_ de longueur 10, tels que <br>
   $\textrm{vect_a}=[5.  ~~5.1 ~~5.2 ~~5.3 ~~5.4 ~~5.5   ~~5.6 ~~5.7 ~~5.8 ~~5.9]$<br>
   et $\textrm{vect_b}=[0.  ~~0.1 ~~0.2 ~~0.3 ~~0.4 ~~0.5   ~~0.6 ~~0.7 ~~0.8 ~~0.9]$

2. Réaliser le produit scalaire (grâce à l'opérateur $\mathtt{@}$, puis $\mathtt{np.dot}$) $Pscal=vect\_a \cdot vect\_b$. Afficher les résultats.

3. Tester l'égalité des deux résultats (boucle $\mathtt{if}$, en affichant le résultat du test (un format peut-être nécessaire pour n'afficher que les chiffres significatifs.)

4. Vérifier la valeur du produit scalaire en réalisant un troisième calcul (on nommera le résultat $\textrm{Pscal_new}$) en utilisant une boucle $\mathtt{for}$. Interpréter le résultat vis-à-vis des erreurs d'arrondis.


In [129]:
# réponse N3
#q1.
vect_a = np.arange(5, 6, 0.1)
vect_b = np.arange(0, 1, 0.1)
print(vect_a)
print(vect_b)

[5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [130]:
#q2.
#Avec le @
produit_scalaire = vect_a @ vect_b
print(produit_scalaire)

#Avec le np.dot
produit_scalaire1 = np.dot(vect_a, vect_b)
print(produit_scalaire1)

25.349999999999987
25.349999999999987


In [131]:
#q3.
result_equal = abs(produit_scalaire  == produit_scalaire1) 
if result_equal:
    print("Les résultats sont égaux!")

Les résultats sont égaux!


In [132]:
#q4.
Pscal_new = 0
for i in range(len(vect_a)):
    Pscal_new += vect_a[i] * vect_b[i]

print("Produit scalaire avec une boucle for :", Pscal_new)

Produit scalaire avec une boucle for : 25.349999999999987


#### #### N4 : Volume de café

<img src="cafe.png" alt="cafe" width="150" align="right"/>

Dans le porte-gobelet du porte-bagage de votre vélo, vous avez imprudemment placé un mug (de diamètre : 7,5 cm) sans couvercle. Celui-ci contient 60 cl de café, et est rempli jusqu'à 10 mm du bord.

1. Calculez la hauteur du mug si vous roulez sur du plat.

2. Si vous habitez sur les hauteurs de la rue Ménilmontant à Paris (pente 14 \%), ou bien San Francisco Filbert Street (pente 31.5 \%), est-il nécessaire de changer de mug pour profiter de son café sur les bancs de l'université ?

La réponse affichée sera OUI ou NON.
Dans tous les cas, vous justifierez votre réponse en précisant la hauteur minimale de mug nécessaire (attention au format de l'affichage).

3. Utilisez une boucle $\mathtt{WHILE}$ pour identifier la pente maximale admissible à 0.5\% près. On commencera par créer le tableau _Numpy_ permettant de parcourir toutes les pentes entre 14 et 31.5\% avec un incrément de 0.5\%.

Remarque : Une pente correspond au rapport entre le dénivelé (hauteur) et la distance horizontale parcourue.


In [133]:
# réponse N4
#q1.
import math


diametre_mug_m = 7.5/ 100  
volume_cafe_l = 60 / 1000   
marge_remplissage_m = 10 / 1000  

aire_base_mug = math.pi * (diametre_mug_m / 2)**2
hauteur_minimale_m = (volume_cafe_l + (aire_base_mug * marge_remplissage_m)) / aire_base_mug

print(hauteur_minimale_m)


13.591221810508403


In [134]:
#q2.
import numpy 
ente_min = 0.14       
pente_max = 0.315      
increment_pente = 0.005  

if hauteur_minimale_m > ente_min*100:
    print("OUI")
else: 
    print("NON")

if hauteur_minimale_m > pente_max*100:
    print("OUI")
else: 
    print("NON")

NON
NON


In [135]:
#q3
pentetab = numpy.arange(pente_min, pente_max + increment_pente, increment_pente)
for pente in pentetab:
    if hauteur_minimale_m > pente:
        print(f"Pente de {pente*100:.1f}% : OUI")
    else:
        print(f"Pente de {pente*100:.1f}% : NON")

NameError: name 'pente_min' is not defined